# Generated by Django 3.2.4 on 2021-06-30 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uzb', models.TextField(verbose_name="O'zbekcha")),
                ('rus', models.TextField(verbose_name='Ruscha')),
            ],
            options={
                'verbose_name': 'Til sozlamasi',
                'verbose_name_plural': 'Til sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=255, verbose_name='Viloyat nomi')),
            ],
            options={
                'verbose_name': 'Viloyat',
                'verbose_name_plural': 'Viloyatlar',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=255, verbose_name='Tuman/shahar nomi')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='language.region')),
            ],
            options={
                'verbose_name': 'Tuman/Shahar',
                'verbose_name_plural': 'Tumanlar/Shaharlar',
            },
        ),
    ]
