# Generated by Django 3.2.4 on 2021-06-30 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('language', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(blank=True, max_length=13, unique=True, verbose_name='Username')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superadmin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_user_id', models.CharField(max_length=255, verbose_name='Mijozning telegram IDsi')),
                ('passport_series', models.CharField(blank=True, max_length=2, null=True, verbose_name='Pasport seriyasi')),
                ('passport_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Pasport raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('is_ordered', models.BooleanField(default=False, null=True, verbose_name='Buyurtma qilingan')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kiritildi')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name="O'zgartirildi")),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, verbose_name='Kategoriya nomi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Mahsulot nomi')),
                ('description', models.TextField(blank=True, verbose_name='Mahsulot haqida')),
                ('price', models.FloatField(default=0.0, verbose_name='Narxi')),
                ('is_active', models.BooleanField(default=True, null=True, verbose_name='Mavjudligi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.category', verbose_name='Kategoriyasi')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=255, verbose_name="To'liq ismi")),
                ('phone', models.CharField(max_length=15, null=True, verbose_name='Telefon raqami')),
                ('user_id', models.IntegerField(default=0, verbose_name='Telegram foydalanuvchi IDsi')),
                ('bot_step', models.CharField(choices=[('MainMenu', 'MainMenu'), ('AskFullname', 'AskFullname'), ('AskPhone', 'AskPhone'), ('AskRegion', 'AskRegion'), ('AskDistrict', 'AskDistrict'), ('ChooseCategory', 'ChooseCategory'), ('ChooseProduct', 'ChooseProduct'), ('Cart', 'Cart'), ('PassportSeries', 'PassportSeries'), ('PassportNumber', 'PassportNumber'), ('Confirmation', 'Confirmation')], default='MainMenu', max_length=255, null=True, verbose_name='Foydalanuvchining botdagi bosqichi')),
                ('lang', models.CharField(default='UZB', max_length=255, null=True, verbose_name='Til')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='language.district', verbose_name='Tumani')),
            ],
            options={
                'verbose_name': 'Mijoz',
                'verbose_name_plural': 'Mijozlar',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Miqdori')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('is_ordered', models.BooleanField(default=False, null=True, verbose_name='Buyurtma qilingan')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kiritildi')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name="O'zgartirildi")),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Buyurtma jihoz',
                'verbose_name_plural': 'Buyurtma jihozlar',
            },
        ),
    ]
