# Generated by Django 3.2.4 on 2021-07-02 11:45

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cart_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo1',
            field=models.ImageField(null=True, upload_to=app.models.get_file_path, verbose_name='Rasm 1'),
        ),
        migrations.AddField(
            model_name='product',
            name='photo2',
            field=models.ImageField(null=True, upload_to=app.models.get_file_path, verbose_name='Rasm 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='photo3',
            field=models.ImageField(null=True, upload_to=app.models.get_file_path, verbose_name='Rasm 3'),
        ),
    ]
