# Generated by Django 3.2.4 on 2021-06-26 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210626_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
        migrations.AddField(
            model_name='client',
            name='bot_step',
            field=models.CharField(choices=[('MainMenu', 'MainMenu'), ('AskFullname', 'AskFullname'), ('AskPhone', 'AskPhone'), ('AskRegion', 'AskRegion'), ('AskDistrict', 'AskDistrict'), ('ChooseCategory', 'ChooseCategory'), ('ChooseProduct', 'ChooseProduct'), ('Cart', 'Cart'), ('MakeContract', 'MakeContract'), ('PassportSeries', 'PassportSeries'), ('PassportNumber', 'PassportNumber'), ('Confirmation', 'Confirmation')], default='MainMenu', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='user_id',
            field=models.IntegerField(default=0, verbose_name='Telegram foydalanuvchi IDsi'),
        ),
        migrations.AlterField(
            model_name='client',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.district', verbose_name='Tumani'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=13, unique=True, verbose_name='Username'),
        ),
    ]
