# Generated by Django 3.2.4 on 2021-06-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210626_2139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Mijoz', 'verbose_name_plural': 'Mijozlar'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name': 'Tuman/Shahar', 'verbose_name_plural': 'Tumanlar/Shaharlar'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Viloyat', 'verbose_name_plural': 'Viloyatlar'},
        ),
        migrations.AddField(
            model_name='client',
            name='lang',
            field=models.CharField(default='UZB', max_length=255, null=True, verbose_name='Til'),
        ),
        migrations.AlterField(
            model_name='client',
            name='bot_step',
            field=models.CharField(choices=[('MainMenu', 'MainMenu'), ('AskFullname', 'AskFullname'), ('AskPhone', 'AskPhone'), ('AskRegion', 'AskRegion'), ('AskDistrict', 'AskDistrict'), ('ChooseCategory', 'ChooseCategory'), ('ChooseProduct', 'ChooseProduct'), ('Cart', 'Cart'), ('MakeContract', 'MakeContract'), ('PassportSeries', 'PassportSeries'), ('PassportNumber', 'PassportNumber'), ('Confirmation', 'Confirmation')], default='MainMenu', max_length=255, null=True, verbose_name='Foydalanuvchining botdagi bosqichi'),
        ),
    ]
