# Generated by Django 3.2.4 on 2021-06-26 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210626_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.district', verbose_name='Tumani'),
        ),
    ]
