# Generated by Django 3.2.4 on 2021-06-27 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_client_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=15, null=True, verbose_name='Telefon raqami'),
        ),
    ]
