# Generated by Django 3.2.4 on 2021-06-27 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_client_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='client',
            name='fullname',
            field=models.CharField(blank=True, max_length=255, verbose_name="To'liq ismi"),
        ),
    ]
