# Generated by Django 3.2.4 on 2021-06-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210630_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='is_ordered',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='client_user_id',
            field=models.CharField(max_length=255, verbose_name='Mijozning telegram IDsi'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
    ]
