# Generated by Django 3.2.4 on 2021-06-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210630_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='passport_number',
            field=models.CharField(max_length=15, null=True, verbose_name='Pasport raqami'),
        ),
        migrations.AddField(
            model_name='cart',
            name='passport_series',
            field=models.CharField(max_length=2, null=True, verbose_name='Pasport seriyasi'),
        ),
        migrations.AlterField(
            model_name='client',
            name='bot_step',
            field=models.CharField(choices=[('MainMenu', 'MainMenu'), ('AskFullname', 'AskFullname'), ('AskPhone', 'AskPhone'), ('AskRegion', 'AskRegion'), ('AskDistrict', 'AskDistrict'), ('ChooseCategory', 'ChooseCategory'), ('ChooseProduct', 'ChooseProduct'), ('Cart', 'Cart'), ('PassportSeries', 'PassportSeries'), ('PassportNumber', 'PassportNumber'), ('Confirmation', 'Confirmation')], default='MainMenu', max_length=255, null=True, verbose_name='Foydalanuvchining botdagi bosqichi'),
        ),
    ]
