# Generated by Django 3.2.4 on 2021-06-30 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_cart_is_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='is_ordered',
            field=models.BooleanField(default=False, null=True, verbose_name='Buyurtma qilingan'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='is_ordered',
            field=models.BooleanField(default=False, null=True, verbose_name='Buyurtma qilingan'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product', verbose_name='Mahsulot'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(verbose_name='Miqdori'),
        ),
    ]
