# Generated by Django 3.2.4 on 2021-06-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210630_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='passport_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Pasport raqami'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='passport_series',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Pasport seriyasi'),
        ),
    ]
