# Generated by Django 3.2.4 on 2021-06-30 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0003_district_region'),
        ('app', '0015_auto_20210630_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='language.district', verbose_name='Tumani'),
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
