# Generated by Django 3.2.4 on 2021-06-30 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210630_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=255, verbose_name='Viloyat nomi')),
            ],
            options={
                'verbose_name': 'Viloyat',
                'verbose_name_plural': 'Viloyatlar',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=255, verbose_name='Tuman/shahar nomi')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.region')),
            ],
            options={
                'verbose_name': 'Tuman/Shahar',
                'verbose_name_plural': 'Tumanlar/Shaharlar',
            },
        ),
        migrations.AlterField(
            model_name='client',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.district', verbose_name='Tumani'),
        ),
    ]
